import '../../app/app_routes.dart';
import 'page_spec.dart';

final Map<String, PageSpec> pageSpecs = <String, PageSpec>{
  AppRoutes.home: PageSpec(
    route: AppRoutes.home,
    title: '主页',
    showBottomTabs: true,
    activeTab: MainTab.home,
    showFab: true,
    sections: <SectionSpec>[
      SectionSpec(
        id: 'top-dashboard',
        title: '今日学习仪表',
        subtitle: '做题 18 · 正确率 72% · 连续学习 6 天',
        type: SectionType.dashboard,
        items: <String>['预测分 63/100', '目标分 70', '建议先补板块运动模型'],
        primaryRoute: AppRoutes.predictionCenter,
        secondaryRoute: AppRoutes.modelTraining,
      ),
      SectionSpec(
        id: 'recommendation-list',
        title: '推荐学习',
        type: SectionType.list,
        items: <String>[
          '待诊断：2025 天津模拟 第 5 题',
          '板块运动 - 决策训练（Step 2）',
          '牛顿第二定律 - 概念辨析',
        ],
        primaryRoute: AppRoutes.aiDiagnosis,
      ),
      SectionSpec(
        id: 'recent-upload',
        title: '最近上传',
        type: SectionType.list,
        items: <String>['今天 18:40 上传 12 题，待诊断 3 题'],
        primaryRoute: AppRoutes.uploadHistory,
      ),
    ],
  ),
  AppRoutes.community: PageSpec(
    route: AppRoutes.community,
    title: '社区',
    showBottomTabs: true,
    activeTab: MainTab.community,
    sections: <SectionSpec>[
      SectionSpec(
        id: 'board-my-requests',
        title: '我的需求',
        type: SectionType.list,
        items: <String>['希望支持按学校题库过滤', '希望题目支持语音讲解'],
      ),
      SectionSpec(
        id: 'board-feature-boost',
        title: '新功能加速',
        type: SectionType.list,
        items: <String>['错题图片 OCR 增强', 'AI 诊断可选“简版/详版”'],
      ),
      SectionSpec(
        id: 'board-feedback',
        title: '改版建议',
        type: SectionType.list,
        items: <String>['顶部筛选可固定', '周复盘图表增加对比线'],
      ),
    ],
  ),
  AppRoutes.globalKnowledge: PageSpec(
    route: AppRoutes.globalKnowledge,
    title: '全局 - 知识点',
    showBottomTabs: true,
    activeTab: MainTab.global,
    topSwitches: <NavTarget>[
      NavTarget(label: '知识点', route: AppRoutes.globalKnowledge),
      NavTarget(label: '模型/方法', route: AppRoutes.globalModel),
      NavTarget(label: '高考卷子', route: AppRoutes.globalExam),
    ],
    sections: <SectionSpec>[
      SectionSpec(
        id: 'knowledge-tree',
        title: '知识点树（可折叠）',
        type: SectionType.tree,
        items: <String>[
          '力学 > 牛顿运动定律 > 牛顿第二定律',
          '力学 > 曲线运动 > 平抛运动',
          '电学 > 恒定电流 > 欧姆定律',
        ],
        primaryRoute: AppRoutes.knowledgeDetail,
      ),
    ],
  ),
  AppRoutes.globalModel: PageSpec(
    route: AppRoutes.globalModel,
    title: '全局 - 模型/方法',
    showBottomTabs: true,
    activeTab: MainTab.global,
    topSwitches: <NavTarget>[
      NavTarget(label: '知识点', route: AppRoutes.globalKnowledge),
      NavTarget(label: '模型/方法', route: AppRoutes.globalModel),
      NavTarget(label: '高考卷子', route: AppRoutes.globalExam),
    ],
    sections: <SectionSpec>[
      SectionSpec(
        id: 'model-tree',
        title: '模型树（可折叠）',
        type: SectionType.tree,
        items: <String>[
          '板块运动模型 > 同向/反向判定',
          '动力学模型 > 受力分析 + 运动学联立',
          '电路模型 > 等效电阻 + 功率分析',
        ],
        primaryRoute: AppRoutes.modelDetail,
      ),
    ],
  ),
  AppRoutes.globalExam: PageSpec(
    route: AppRoutes.globalExam,
    title: '全局 - 高考卷子',
    showBottomTabs: true,
    activeTab: MainTab.global,
    topSwitches: <NavTarget>[
      NavTarget(label: '知识点', route: AppRoutes.globalKnowledge),
      NavTarget(label: '模型/方法', route: AppRoutes.globalModel),
      NavTarget(label: '高考卷子', route: AppRoutes.globalExam),
    ],
    sections: <SectionSpec>[
      SectionSpec(
        id: 'exam-heatmap',
        title: '卷面热力图',
        subtitle: '参数可驱动渲染（题号、得分率、掌握等级）',
        type: SectionType.heatmap,
        matrix: <List<String>>[
          <String>['稳', '稳', '警', '优', '险'],
          <String>['优', '警', '稳', '险', '优'],
          <String>['警', '优', '稳', '稳', '险'],
        ],
        primaryRoute: AppRoutes.questionAggregate,
      ),
      SectionSpec(
        id: 'question-type-browser',
        title: '按题型浏览',
        type: SectionType.list,
        items: <String>['选择题（运动学）', '实验题（电学）', '计算题（动力学）'],
        primaryRoute: AppRoutes.questionAggregate,
        secondaryRoute: AppRoutes.uploadMenu,
      ),
      SectionSpec(
        id: 'recent-exams',
        title: '最近卷子',
        type: SectionType.list,
        items: <String>['2025 天津一模', '2025 河北联考', '2024 全国卷模拟'],
        primaryRoute: AppRoutes.uploadHistory,
      ),
    ],
  ),
  AppRoutes.memory: PageSpec(
    route: AppRoutes.memory,
    title: '记忆',
    showBottomTabs: true,
    activeTab: MainTab.memory,
    sections: <SectionSpec>[
      SectionSpec(
        id: 'review-dashboard',
        title: '今日复习情况',
        subtitle: '待复习 24 张 · 已完成 13 张',
        type: SectionType.dashboard,
        items: <String>['记住率 78%', '连续复习 6 天', '累计卡片 420'],
        primaryRoute: AppRoutes.flashcardReview,
      ),
      SectionSpec(
        id: 'card-category-list',
        title: '卡片分类',
        type: SectionType.list,
        items: <String>['力学 102', '电学 94', '热学 33', '实验 27'],
      ),
    ],
  ),
  AppRoutes.profile: PageSpec(
    route: AppRoutes.profile,
    title: '我的',
    showBottomTabs: true,
    activeTab: MainTab.profile,
    sections: <SectionSpec>[
      SectionSpec(
        id: 'user-info-card',
        title: '用户信息',
        subtitle: '高三（1）班 · 目标 70+',
        type: SectionType.dashboard,
        items: <String>['昵称：小宇', '年级排名：Top 18%', '本周学习时长：9h'],
      ),
      SectionSpec(
        id: 'target-score-card',
        title: '目标分数',
        type: SectionType.dashboard,
        items: <String>['当前预测分 63', '目标分 70', '差距 7 分'],
      ),
      SectionSpec(
        id: 'three-row-navigation',
        title: '常用入口',
        type: SectionType.list,
        items: <String>['上传历史', '周复盘', '学习策略登记'],
        primaryRoute: AppRoutes.uploadHistory,
      ),
      SectionSpec(
        id: 'two-row-navigation',
        title: '扩展入口',
        type: SectionType.list,
        items: <String>['消息中心', '学习提醒'],
      ),
      SectionSpec(
        id: 'learning-stats',
        title: '学习统计',
        type: SectionType.tags,
        tags: <String>['诊断完成 126', '模型训练 84', '知识学习 73', '本周新增错题 18'],
      ),
    ],
  ),
  AppRoutes.uploadHistory: PageSpec(
    route: AppRoutes.uploadHistory,
    title: '上传历史',
    backRoute: AppRoutes.home,
    sections: <SectionSpec>[
      SectionSpec(
        id: 'history-filter',
        title: '筛选器',
        type: SectionType.tags,
        tags: <String>['全部', '待诊断', '已完成', '作业', '考试'],
      ),
      SectionSpec(
        id: 'history-date-scroll',
        title: '按日期滚动排序',
        type: SectionType.timeline,
        items: <String>['今天', '2月20日', '2月19日', '2月18日'],
      ),
      SectionSpec(
        id: 'history-record-list',
        title: '做题历史列表',
        type: SectionType.list,
        items: <String>[
          'HW 2025 天津模拟 第5题（待诊断）',
          'EX 2024 全国卷 第21题（已完成）',
          'QK 受力分析专项（已完成）',
        ],
        primaryRoute: AppRoutes.questionDetail,
      ),
    ],
  ),
  AppRoutes.questionAggregate: PageSpec(
    route: AppRoutes.questionAggregate,
    title: '单题统计',
    backRoute: AppRoutes.globalExam,
    sections: <SectionSpec>[
      SectionSpec(
        id: 'single-question-dashboard',
        title: '题号统计 Dashboard',
        subtitle: '做题 12 次 · 正确率 58% · 预测得分 +3.2',
        type: SectionType.dashboard,
        items: <String>['薄弱：板块运动模型', '建议：先做决策训练'],
      ),
      SectionSpec(
        id: 'exam-analysis',
        title: '考情分析',
        type: SectionType.tags,
        tags: <String>['审题偏快', '列式遗漏', '单位错误', '符号方向错'],
      ),
      SectionSpec(
        id: 'question-history-list',
        title: '做过的题列表',
        type: SectionType.list,
        items: <String>['2025 天津一模 第5题', '2025 河北联考 第6题', '2024 模拟卷 第8题'],
        primaryRoute: AppRoutes.questionDetail,
      ),
    ],
  ),
  AppRoutes.questionDetail: PageSpec(
    route: AppRoutes.questionDetail,
    title: '题目详情',
    backRoute: AppRoutes.questionAggregate,
    sections: <SectionSpec>[
      SectionSpec(
        id: 'question-content',
        title: '题库题目',
        type: SectionType.placeholder,
        subtitle: '展示题图/题干/关键条件（与 HTML 页一致）',
      ),
      SectionSpec(
        id: 'answer-result',
        title: '答题结果',
        type: SectionType.dashboard,
        items: <String>['结果：错误', '失分原因：模型选择偏差'],
        primaryRoute: AppRoutes.aiDiagnosis,
      ),
      SectionSpec(
        id: 'question-relations',
        title: '题目关联',
        type: SectionType.tags,
        tags: <String>['模型：板块运动', '知识点：牛顿第二定律', '知识点：受力分析'],
        primaryRoute: AppRoutes.modelDetail,
        secondaryRoute: AppRoutes.knowledgeDetail,
      ),
      SectionSpec(
        id: 'question-source',
        title: '题目来源',
        type: SectionType.list,
        items: <String>['来源：2025 天津模拟卷', '上传时间：今天 18:40'],
      ),
    ],
  ),
  AppRoutes.aiDiagnosis: PageSpec(
    route: AppRoutes.aiDiagnosis,
    title: 'AI 诊断',
    backRoute: AppRoutes.questionDetail,
    showChatInput: true,
    sections: <SectionSpec>[
      SectionSpec(
        id: 'main-content',
        title: '诊断对话',
        type: SectionType.chat,
        items: <String>[
          'AI：你第一步如何判断相对运动状态？',
          '我：先分析两个物体受力。',
          'AI：很好，接下来判断速度方向与大小。',
        ],
        primaryRoute: AppRoutes.modelTraining,
        secondaryRoute: AppRoutes.questionDetail,
      ),
    ],
  ),
  AppRoutes.modelDetail: PageSpec(
    route: AppRoutes.modelDetail,
    title: '模型详情',
    backRoute: AppRoutes.globalModel,
    sections: <SectionSpec>[
      SectionSpec(
        id: 'mastery-dashboard',
        title: '模型掌握度 Dashboard',
        subtitle: '当前等级：L2 薄弱',
        type: SectionType.dashboard,
        items: <String>['近7天训练 4 次', '正确率 61%'],
        primaryRoute: AppRoutes.modelTraining,
      ),
      SectionSpec(
        id: 'prerequisite-knowledge-list',
        title: '前置知识点列表',
        type: SectionType.list,
        items: <String>['受力分析', '牛顿第二定律', '相对运动'],
        primaryRoute: AppRoutes.knowledgeDetail,
      ),
      SectionSpec(
        id: 'related-question-list',
        title: '相关题目列表',
        type: SectionType.list,
        items: <String>['2025 天津模拟 第5题', '2024 全国卷 第21题'],
        primaryRoute: AppRoutes.questionDetail,
      ),
      SectionSpec(
        id: 'training-record-list',
        title: '训练记录列表',
        type: SectionType.timeline,
        items: <String>['Step2 决策训练：已完成', 'Step3 列式训练：待完成'],
      ),
    ],
  ),
  AppRoutes.modelTraining: PageSpec(
    route: AppRoutes.modelTraining,
    title: '板块运动 - 训练',
    backRoute: AppRoutes.modelDetail,
    stageSteps: <String>['识别训练', '决策训练', '列式训练', '陷阱辨析', '完整求解', '变式训练'],
    initialStageIndex: 1,
    showChatInput: true,
    sections: <SectionSpec>[
      SectionSpec(
        id: 'training-dialogue',
        title: '训练对话区',
        type: SectionType.chat,
        items: <String>['AI：面对这类题，第一步做什么？', '我：先判断相对状态。', 'AI：很好，下一步进入决策训练。'],
      ),
    ],
  ),
  AppRoutes.knowledgeDetail: PageSpec(
    route: AppRoutes.knowledgeDetail,
    title: '知识点详情',
    backRoute: AppRoutes.globalKnowledge,
    sections: <SectionSpec>[
      SectionSpec(
        id: 'mastery-dashboard',
        title: '当前掌握度总结 Dashboard',
        subtitle: '当前等级：L3 待巩固',
        type: SectionType.dashboard,
        items: <String>['概念检测通过率 74%', '建议先做辨析训练'],
        primaryRoute: AppRoutes.knowledgeLearning,
      ),
      SectionSpec(
        id: 'concept-test-records',
        title: '概念检测记录',
        type: SectionType.list,
        items: <String>['2月20日：通过', '2月18日：未通过'],
      ),
      SectionSpec(
        id: 'related-models',
        title: '关联模型',
        type: SectionType.list,
        items: <String>['板块运动模型', '圆周运动模型'],
        primaryRoute: AppRoutes.modelDetail,
      ),
    ],
  ),
  AppRoutes.knowledgeLearning: PageSpec(
    route: AppRoutes.knowledgeLearning,
    title: '知识点学习',
    backRoute: AppRoutes.knowledgeDetail,
    stageSteps: <String>['概念呈现', '理解检查', '辨析训练', '实际应用', '概念检测'],
    initialStageIndex: 2,
    showChatInput: true,
    sections: <SectionSpec>[
      SectionSpec(
        id: 'learning-dialogue',
        title: '学习对话区',
        type: SectionType.chat,
        items: <String>[
          'AI：请比较两个物体在同一时刻的加速度。',
          '我：先判断受力，再看质量。',
          'AI：很好，这一步是辨析训练核心。',
        ],
      ),
    ],
  ),
  AppRoutes.flashcardReview: PageSpec(
    route: AppRoutes.flashcardReview,
    title: '闪卡复习',
    backRoute: AppRoutes.memory,
    sections: <SectionSpec>[
      SectionSpec(
        id: 'flashcard',
        title: '闪卡',
        subtitle: '点击翻转，完成后给出记忆反馈',
        type: SectionType.flashcard,
        items: <String>['正面：什么是牛顿第二定律？', '反面：F = ma'],
      ),
    ],
  ),
  AppRoutes.predictionCenter: PageSpec(
    route: AppRoutes.predictionCenter,
    title: '预测中心',
    backRoute: AppRoutes.home,
    sections: <SectionSpec>[
      SectionSpec(
        id: 'score-card',
        title: '预测分数卡片',
        type: SectionType.dashboard,
        items: <String>['63 / 100', '目标 70', '差距 7'],
      ),
      SectionSpec(
        id: 'trend-card',
        title: '预测分数趋势卡片',
        type: SectionType.timeline,
        items: <String>['01/20: 55', '01/27: 57', '02/03: 59', '02/10: 63'],
      ),
      SectionSpec(
        id: 'score-path-table',
        title: '提分路径表格',
        type: SectionType.table,
        tableHeaders: <String>['模块', '问题', '动作', '预估+分'],
        tableRows: <List<String>>[
          <String>['板块运动', '决策偏差', '先做 Step2', '+2.0'],
          <String>['受力分析', '漏受力', '每日 5 题', '+1.5'],
          <String>['审题', '信息遗漏', '关键词标注', '+1.0'],
        ],
        primaryRoute: AppRoutes.questionAggregate,
      ),
      SectionSpec(
        id: 'priority-model-list',
        title: '优先训练模型',
        type: SectionType.list,
        items: <String>['板块运动模型', '动力学联立模型', '电路功率模型'],
        primaryRoute: AppRoutes.modelDetail,
      ),
    ],
  ),
  AppRoutes.weeklyReview: PageSpec(
    route: AppRoutes.weeklyReview,
    title: '周复盘',
    backRoute: AppRoutes.profile,
    sections: <SectionSpec>[
      SectionSpec(
        id: 'weekly-dashboard',
        title: '本周做题 Dashboard',
        type: SectionType.dashboard,
        items: <String>['总做题 86', '诊断完成 22', '训练完成 18'],
      ),
      SectionSpec(
        id: 'score-change',
        title: '分数变化',
        type: SectionType.timeline,
        items: <String>['周初 58', '周中 61', '周末 63'],
      ),
      SectionSpec(
        id: 'weekly-progress',
        title: '本周进展',
        type: SectionType.list,
        items: <String>['板块运动模型从 L1 -> L2', '受力分析概念检测通过'],
      ),
      SectionSpec(
        id: 'next-week-focus',
        title: '下周重点',
        type: SectionType.list,
        items: <String>['优先补板块运动 Step3', '每天复习 20 张闪卡'],
      ),
    ],
  ),
  AppRoutes.uploadMenu: PageSpec(
    route: AppRoutes.uploadMenu,
    title: '上传菜单',
    backRoute: AppRoutes.home,
    sections: <SectionSpec>[
      SectionSpec(
        id: 'main-content',
        title: '建设中',
        subtitle: '此页为上传入口占位，保持路由闭环。',
        type: SectionType.placeholder,
      ),
    ],
  ),
  AppRoutes.registerStrategy: PageSpec(
    route: AppRoutes.registerStrategy,
    title: '学习策略登记',
    backRoute: AppRoutes.profile,
    sections: <SectionSpec>[
      SectionSpec(
        id: 'main-content',
        title: '建设中',
        subtitle: '此页为策略登记占位，保持路由闭环。',
        type: SectionType.placeholder,
      ),
    ],
  ),
};
